const API_ACCESS_CLIENTS_TABLE_NAME = 'api_access_clients'
const API_ACCESS_TOKENS_TABLE_NAME = 'api_access_tokens'
const CLIENTS_ACCESS_TABLE_NAME = 'clients_access'

const DOWN_DETECTOR_SEARCH_NOW = 'downdetector_search_now'
const DOWN_DETECTOR_CHANGE_TABLE_NAME = 'downdetector_change'
const DOWN_DETECTOR_HIST_TABLE_NAME = 'downdetector_hist'
const DOWN_DETECTOR_ROUTINE_EXECUTION = 'down_detector_routine_execution'

const MONITORING_TABLE_NAME = 'monitoring'
const PERMISSIONS_TABLE_NAME = 'permissions'
const SERVICES_TABLE_NAME = 'services'
const SERVICES_UPDATE_TIME_TABLE_NAME = 'services_update_time'
const USERS_ACCESS_TABLE_NAME = 'users_access'
const USERS_TABLE_NAME = 'users'

const CPFL_DATA = 'cpfl_data'
const CPFL_SEARCH = 'cpfl_search'
const CPFL_SEARCH_UPDATE_TIME = 'cpfl_search_update_time'
const CPFL_SEARCH_NOW = 'cpfl_search_now'

const EQUATORIAL_DATA = 'equatorial_data'

const ENERGISA_INFORMATIONS_TABLE_NAME = 'energisa_informations'
const ENERGISA_DATA_TABLE_NAME = 'energisa_data'

const OCR_DATA_TABLE_NAME = 'ocr_data'
const OCR_PERMISSIONS = 'ocr_permissions'
const OCR_SERVICES = 'ocr_services'

const ENERGY_PERMISSIONS_TABLE_NAME = 'energy_permissions'

const HOSTS_PERFIS_TABLE_NAME = 'hosts_perfis'

module.exports = {
  API_ACCESS_CLIENTS_TABLE_NAME,
  API_ACCESS_TOKENS_TABLE_NAME,
  CLIENTS_ACCESS_TABLE_NAME,

  DOWN_DETECTOR_CHANGE_TABLE_NAME,
  DOWN_DETECTOR_HIST_TABLE_NAME,
  DOWN_DETECTOR_ROUTINE_EXECUTION,
  MONITORING_TABLE_NAME,
  PERMISSIONS_TABLE_NAME,
  SERVICES_TABLE_NAME,
  SERVICES_UPDATE_TIME_TABLE_NAME,

  USERS_ACCESS_TABLE_NAME,
  USERS_TABLE_NAME,

  CPFL_DATA,
  CPFL_SEARCH,
  CPFL_SEARCH_UPDATE_TIME,
  CPFL_SEARCH_NOW,

  EQUATORIAL_DATA,

  ENERGISA_INFORMATIONS_TABLE_NAME,
  ENERGISA_DATA_TABLE_NAME,

  OCR_DATA_TABLE_NAME,
  OCR_PERMISSIONS,
  OCR_SERVICES,

  ENERGY_PERMISSIONS_TABLE_NAME,

  HOSTS_PERFIS_TABLE_NAME
}
