const DOWN_DETECTOR_CHANGE_TABLE_NAME = 'downdetector_change'
const DOWN_DETECTOR_HIST_TABLE_NAME = 'downdetector_hist'
const MONITORING_TABLE_NAME = 'monitoring'
const SERVICES_TABLE_NAME = 'services'
const USERS_TABLE_NAME = 'users'

module.exports = {
  DOWN_DETECTOR_CHANGE_TABLE_NAME,
  DOWN_DETECTOR_HIST_TABLE_NAME,
  MONITORING_TABLE_NAME,
  SERVICES_TABLE_NAME,
  USERS_TABLE_NAME
}